import type { ReligionId } from "./religions"

export type Holiday = {
  id: string
  religion: ReligionId
  /** ISO date string YYYY-MM-DD in the Gregorian calendar */
  date: string
  /** Name in the original language (transliterated if non-latin script) */
  nameOriginal: string
  /** Portuguese translation / common name */
  namePt: string
  /** Short description in Portuguese (max 2 lines) */
  description: string
  /** Date as expressed in the native calendar */
  nativeDate: string
  major?: boolean
}

// Holidays for 2026 (Gregorian). Movable dates are pre-calculated.
export const HOLIDAYS: Holiday[] = [
  // ==== CRISTIANISMO (Católico / Protestante) ====
  {
    id: "ch-maria",
    religion: "christianity",
    date: "2026-01-01",
    nameOriginal: "Sollemnitas Sanctae Dei Genetricis Mariae",
    namePt: "Solenidade de Santa Maria, Mãe de Deus",
    description: "Celebração católica da maternidade divina de Maria, marcando o início do ano litúrgico.",
    nativeDate: "1 de janeiro",
    major: true,
  },
  {
    id: "ch-epiphany",
    religion: "christianity",
    date: "2026-01-06",
    nameOriginal: "Epiphania Domini",
    namePt: "Epifania do Senhor",
    description: "Manifestação de Cristo aos gentios, representada pela visita dos Reis Magos.",
    nativeDate: "6 de janeiro",
    major: true,
  },
  {
    id: "ch-ash",
    religion: "christianity",
    date: "2026-02-18",
    nameOriginal: "Feria Quarta Cinerum",
    namePt: "Quarta-feira de Cinzas",
    description: "Início da Quaresma, período de 40 dias de preparação para a Páscoa.",
    nativeDate: "18 de fevereiro",
  },
  {
    id: "ch-palm",
    religion: "christianity",
    date: "2026-03-29",
    nameOriginal: "Dominica in Palmis",
    namePt: "Domingo de Ramos",
    description: "Início da Semana Santa, comemorando a entrada de Jesus em Jerusalém.",
    nativeDate: "29 de março",
  },
  {
    id: "ch-maundy",
    religion: "christianity",
    date: "2026-04-02",
    nameOriginal: "Feria Quinta in Cena Domini",
    namePt: "Quinta-feira Santa",
    description: "Comemoração da Última Ceia e instituição da Eucaristia.",
    nativeDate: "2 de abril",
  },
  {
    id: "ch-goodfriday",
    religion: "christianity",
    date: "2026-04-03",
    nameOriginal: "Feria Sexta in Passione Domini",
    namePt: "Sexta-feira Santa",
    description: "Dia da Paixão e Morte de Cristo.",
    nativeDate: "3 de abril",
    major: true,
  },
  {
    id: "ch-easter",
    religion: "christianity",
    date: "2026-04-05",
    nameOriginal: "Pascha",
    namePt: "Páscoa",
    description: "Ressurreição de Cristo, principal festa do cristianismo.",
    nativeDate: "5 de abril",
    major: true,
  },
  {
    id: "ch-ascension",
    religion: "christianity",
    date: "2026-05-14",
    nameOriginal: "Ascensio Domini",
    namePt: "Ascensão do Senhor",
    description: "Comemoração da subida de Cristo ao céu, quarenta dias após a Páscoa.",
    nativeDate: "14 de maio",
  },
  {
    id: "ch-pentecost",
    religion: "christianity",
    date: "2026-05-24",
    nameOriginal: "Pentecostes",
    namePt: "Pentecostes",
    description: "Descida do Espírito Santo sobre os apóstolos, cinquenta dias após a Páscoa.",
    nativeDate: "24 de maio",
    major: true,
  },
  {
    id: "ch-assumption",
    religion: "christianity",
    date: "2026-08-15",
    nameOriginal: "Assumptio Beatae Mariae Virginis",
    namePt: "Assunção de Maria",
    description: "Celebração da elevação de Maria ao céu, em corpo e alma.",
    nativeDate: "15 de agosto",
  },
  {
    id: "ch-allsaints",
    religion: "christianity",
    date: "2026-11-01",
    nameOriginal: "Sollemnitas Omnium Sanctorum",
    namePt: "Dia de Todos os Santos",
    description: "Homenagem a todos os santos conhecidos e desconhecidos da Igreja.",
    nativeDate: "1 de novembro",
  },
  {
    id: "ch-christmas",
    religion: "christianity",
    date: "2026-12-25",
    nameOriginal: "Nativitas Domini",
    namePt: "Natal",
    description: "Celebração do nascimento de Jesus Cristo em Belém.",
    nativeDate: "25 de dezembro",
    major: true,
  },

  // ==== JUDAÍSMO ====
  {
    id: "jd-tubishvat",
    religion: "judaism",
    date: "2026-02-02",
    nameOriginal: "Tu BiShvat",
    namePt: "Ano Novo das Árvores",
    description: "Festa do ano novo ecológico, celebrando a natureza e as árvores.",
    nativeDate: "15 de Shevat, 5786",
  },
  {
    id: "jd-purim",
    religion: "judaism",
    date: "2026-03-03",
    nameOriginal: "Purim",
    namePt: "Festa das Sortes",
    description: "Celebração da salvação do povo judeu narrada no Livro de Ester.",
    nativeDate: "14 de Adar, 5786",
    major: true,
  },
  {
    id: "jd-pesach",
    religion: "judaism",
    date: "2026-04-02",
    nameOriginal: "Pesach",
    namePt: "Páscoa Judaica",
    description: "Festa da libertação do povo hebreu da escravidão no Egito.",
    nativeDate: "15 de Nissan, 5786",
    major: true,
  },
  {
    id: "jd-pesach-end",
    religion: "judaism",
    date: "2026-04-09",
    nameOriginal: "Shvi'i shel Pesach",
    namePt: "Sétimo dia de Pessach",
    description: "Último dia da festa, lembra a travessia do Mar Vermelho.",
    nativeDate: "21 de Nissan, 5786",
  },
  {
    id: "jd-yomhashoah",
    religion: "judaism",
    date: "2026-04-14",
    nameOriginal: "Yom HaShoah",
    namePt: "Dia da Memória do Holocausto",
    description: "Comemoração das vítimas do Holocausto e da resistência judaica.",
    nativeDate: "27 de Nissan, 5786",
  },
  {
    id: "jd-shavuot",
    religion: "judaism",
    date: "2026-05-22",
    nameOriginal: "Shavuot",
    namePt: "Festa das Semanas",
    description: "Comemora a entrega da Torá no Monte Sinai.",
    nativeDate: "6 de Sivan, 5786",
    major: true,
  },
  {
    id: "jd-tishabav",
    religion: "judaism",
    date: "2026-07-23",
    nameOriginal: "Tisha B'Av",
    namePt: "Nono dia de Av",
    description: "Jejum que lembra a destruição dos dois Templos de Jerusalém.",
    nativeDate: "9 de Av, 5786",
  },
  {
    id: "jd-roshhashana",
    religion: "judaism",
    date: "2026-09-12",
    nameOriginal: "Rosh Hashaná",
    namePt: "Ano Novo Judaico",
    description: "Início do ano judaico 5787 e dos Dias de Temor.",
    nativeDate: "1 de Tishrei, 5787",
    major: true,
  },
  {
    id: "jd-yomkippur",
    religion: "judaism",
    date: "2026-09-21",
    nameOriginal: "Yom Kippur",
    namePt: "Dia do Perdão",
    description: "Dia mais sagrado do ano judaico, dedicado ao jejum e ao arrependimento.",
    nativeDate: "10 de Tishrei, 5787",
    major: true,
  },
  {
    id: "jd-sukkot",
    religion: "judaism",
    date: "2026-09-26",
    nameOriginal: "Sukkot",
    namePt: "Festa dos Tabernáculos",
    description: "Lembra a peregrinação no deserto em cabanas após o Êxodo.",
    nativeDate: "15 de Tishrei, 5787",
  },
  {
    id: "jd-simchat",
    religion: "judaism",
    date: "2026-10-04",
    nameOriginal: "Simchat Torah",
    namePt: "Alegria da Torá",
    description: "Encerramento e reinício do ciclo anual de leitura da Torá.",
    nativeDate: "23 de Tishrei, 5787",
  },
  {
    id: "jd-hanukkah",
    religion: "judaism",
    date: "2026-12-05",
    nameOriginal: "Chanukah",
    namePt: "Festa das Luzes",
    description: "Oito dias celebrando a rededicação do Segundo Templo.",
    nativeDate: "25 de Kislev, 5787",
    major: true,
  },

  // ==== ORTODOXOS (Calendário Juliano) ====
  {
    id: "or-christmas",
    religion: "orthodox",
    date: "2026-01-07",
    nameOriginal: "Χριστούγεννα",
    namePt: "Natal Ortodoxo",
    description: "Celebração do nascimento de Cristo segundo o calendário juliano.",
    nativeDate: "25 de dezembro (Juliano)",
    major: true,
  },
  {
    id: "or-theophany",
    religion: "orthodox",
    date: "2026-01-19",
    nameOriginal: "Θεοφάνεια",
    namePt: "Teofania",
    description: "Batismo de Cristo no rio Jordão e manifestação da Trindade.",
    nativeDate: "6 de janeiro (Juliano)",
    major: true,
  },
  {
    id: "or-lent",
    religion: "orthodox",
    date: "2026-02-23",
    nameOriginal: "Μεγάλη Τεσσαρακοστή",
    namePt: "Início da Grande Quaresma",
    description: "Início do período de jejum que antecede a Páscoa Ortodoxa.",
    nativeDate: "23 de fevereiro",
  },
  {
    id: "or-annunciation",
    religion: "orthodox",
    date: "2026-04-07",
    nameOriginal: "Εὐαγγελισμός",
    namePt: "Anunciação",
    description: "Anúncio do Arcanjo Gabriel à Virgem Maria.",
    nativeDate: "25 de março (Juliano)",
  },
  {
    id: "or-easter",
    religion: "orthodox",
    date: "2026-04-12",
    nameOriginal: "Πάσχα",
    namePt: "Páscoa Ortodoxa",
    description: "Ressurreição de Cristo segundo o cálculo juliano.",
    nativeDate: "12 de abril",
    major: true,
  },
  {
    id: "or-ascension",
    religion: "orthodox",
    date: "2026-05-21",
    nameOriginal: "Ἀνάληψις",
    namePt: "Ascensão",
    description: "Quarenta dias após a Páscoa Ortodoxa.",
    nativeDate: "21 de maio",
  },
  {
    id: "or-pentecost",
    religion: "orthodox",
    date: "2026-05-31",
    nameOriginal: "Πεντηκοστή",
    namePt: "Pentecostes Ortodoxo",
    description: "Descida do Espírito Santo, cinquenta dias após a Páscoa.",
    nativeDate: "31 de maio",
  },
  {
    id: "or-transfiguration",
    religion: "orthodox",
    date: "2026-08-19",
    nameOriginal: "Μεταμόρφωσις",
    namePt: "Transfiguração",
    description: "Transfiguração de Cristo no Monte Tabor.",
    nativeDate: "6 de agosto (Juliano)",
  },
  {
    id: "or-dormition",
    religion: "orthodox",
    date: "2026-08-28",
    nameOriginal: "Κοίμησις τῆς Θεοτόκου",
    namePt: "Dormição da Theotókos",
    description: "Adormecimento e elevação da Mãe de Deus.",
    nativeDate: "15 de agosto (Juliano)",
    major: true,
  },

  // ==== ISLAMISMO (Hijri 1447 → 1448) ====
  {
    id: "is-israamiraj",
    religion: "islam",
    date: "2026-01-16",
    nameOriginal: "Al-Isrā' wal-Miʿrāj",
    namePt: "Viagem Noturna e Ascensão",
    description: "Comemora a viagem milagrosa do Profeta Maomé a Jerusalém e ao céu.",
    nativeDate: "27 de Rajab, 1447 AH",
  },
  {
    id: "is-ramadan",
    religion: "islam",
    date: "2026-02-18",
    nameOriginal: "Ramaḍān",
    namePt: "Início do Ramadã",
    description: "Início do mês sagrado de jejum, oração e reflexão.",
    nativeDate: "1 de Ramadan, 1447 AH",
    major: true,
  },
  {
    id: "is-laylatalqadr",
    religion: "islam",
    date: "2026-03-15",
    nameOriginal: "Laylat al-Qadr",
    namePt: "Noite do Decreto",
    description: "Noite em que se acredita ter sido revelado o Alcorão.",
    nativeDate: "27 de Ramadan, 1447 AH",
  },
  {
    id: "is-eidalfitr",
    religion: "islam",
    date: "2026-03-20",
    nameOriginal: "ʿĪd al-Fiṭr",
    namePt: "Festa do Fim do Jejum",
    description: "Celebração que marca o fim do mês do Ramadã.",
    nativeDate: "1 de Shawwal, 1447 AH",
    major: true,
  },
  {
    id: "is-eidaladha",
    religion: "islam",
    date: "2026-05-27",
    nameOriginal: "ʿĪd al-Aḍḥā",
    namePt: "Festa do Sacrifício",
    description: "Comemora o sacrifício de Abraão e encerra o Hajj.",
    nativeDate: "10 de Dhu al-Hijjah, 1447 AH",
    major: true,
  },
  {
    id: "is-newyear",
    religion: "islam",
    date: "2026-06-17",
    nameOriginal: "Ra's as-Sanah al-Hijriyyah",
    namePt: "Ano Novo Islâmico",
    description: "Início do ano 1448 da Hégira.",
    nativeDate: "1 de Muharram, 1448 AH",
    major: true,
  },
  {
    id: "is-ashura",
    religion: "islam",
    date: "2026-06-26",
    nameOriginal: "ʿĀshūrāʾ",
    namePt: "Dia de Ashura",
    description: "Dia de jejum voluntário para sunitas; luto pelo martírio de Husayn para xiitas.",
    nativeDate: "10 de Muharram, 1448 AH",
  },
  {
    id: "is-mawlid",
    religion: "islam",
    date: "2026-08-25",
    nameOriginal: "Mawlid an-Nabī",
    namePt: "Nascimento do Profeta",
    description: "Comemoração do nascimento do Profeta Maomé.",
    nativeDate: "12 de Rabi' al-Awwal, 1448 AH",
  },

  // ==== HINDUÍSMO ====
  {
    id: "hi-makar",
    religion: "hinduism",
    date: "2026-01-14",
    nameOriginal: "Makara Saṅkrānti",
    namePt: "Trânsito para Capricórnio",
    description: "Festival solar que marca o início da colheita e o caminho do sol para o norte.",
    nativeDate: "Magha Śukla, Vikram 2082",
  },
  {
    id: "hi-shivaratri",
    religion: "hinduism",
    date: "2026-02-15",
    nameOriginal: "Mahā Śivarātri",
    namePt: "Grande Noite de Shiva",
    description: "Noite dedicada à vigília e adoração do deus Shiva.",
    nativeDate: "Chaturdashi de Phalguna",
    major: true,
  },
  {
    id: "hi-holi",
    religion: "hinduism",
    date: "2026-03-04",
    nameOriginal: "Holī",
    namePt: "Festival das Cores",
    description: "Festa da primavera que celebra a vitória do bem sobre o mal.",
    nativeDate: "Purnima de Phalguna, Vikram 2082",
    major: true,
  },
  {
    id: "hi-ramanavami",
    religion: "hinduism",
    date: "2026-03-27",
    nameOriginal: "Rāma Navamī",
    namePt: "Nascimento de Rama",
    description: "Celebração do nascimento do deus Rama, sétimo avatar de Vishnu.",
    nativeDate: "Navami de Chaitra",
  },
  {
    id: "hi-hanuman",
    religion: "hinduism",
    date: "2026-04-02",
    nameOriginal: "Hanumān Jayantī",
    namePt: "Nascimento de Hanuman",
    description: "Celebra o nascimento do deus-macaco Hanuman, devoto de Rama.",
    nativeDate: "Purnima de Chaitra",
  },
  {
    id: "hi-raksha",
    religion: "hinduism",
    date: "2026-08-28",
    nameOriginal: "Rakṣā Bandhan",
    namePt: "Laço de Proteção",
    description: "Celebra o vínculo sagrado entre irmãos e irmãs.",
    nativeDate: "Purnima de Shravana",
  },
  {
    id: "hi-janmashtami",
    religion: "hinduism",
    date: "2026-09-04",
    nameOriginal: "Kṛṣṇa Janmāṣṭamī",
    namePt: "Nascimento de Krishna",
    description: "Celebra o nascimento de Krishna, oitavo avatar de Vishnu.",
    nativeDate: "Ashtami de Bhadrapada",
    major: true,
  },
  {
    id: "hi-ganesh",
    religion: "hinduism",
    date: "2026-09-14",
    nameOriginal: "Gaṇeśa Caturthī",
    namePt: "Festival de Ganesha",
    description: "Comemoração do nascimento do deus com cabeça de elefante.",
    nativeDate: "Chaturthi de Bhadrapada",
  },
  {
    id: "hi-navaratri",
    religion: "hinduism",
    date: "2026-10-11",
    nameOriginal: "Navarātri",
    namePt: "Nove Noites da Deusa",
    description: "Nove noites de culto às formas da Deusa Durga.",
    nativeDate: "Pratipada de Ashwin",
    major: true,
  },
  {
    id: "hi-dussehra",
    religion: "hinduism",
    date: "2026-10-20",
    nameOriginal: "Vijayādaśamī",
    namePt: "Dia da Vitória",
    description: "Celebra a vitória de Rama sobre Ravana e o triunfo do bem.",
    nativeDate: "Dashami de Ashwin",
  },
  {
    id: "hi-diwali",
    religion: "hinduism",
    date: "2026-11-08",
    nameOriginal: "Dīpāvalī",
    namePt: "Festival das Luzes",
    description: "Cinco dias que celebram a vitória da luz sobre a escuridão.",
    nativeDate: "Amavasya de Kartika",
    major: true,
  },

  // ==== TRADIÇÃO CHINESA ====
  {
    id: "cn-newyear",
    religion: "chinese",
    date: "2026-02-17",
    nameOriginal: "春節 Chūn Jié",
    namePt: "Ano Novo Chinês",
    description: "Ano do Cavalo de Fogo. Festival da primavera, principal festa do calendário lunar.",
    nativeDate: "1 do 1º mês lunar, 4724",
    major: true,
  },
  {
    id: "cn-lantern",
    religion: "chinese",
    date: "2026-03-03",
    nameOriginal: "元宵節 Yuánxiāo Jié",
    namePt: "Festival das Lanternas",
    description: "Fim das celebrações do Ano Novo com lanternas e doces de arroz.",
    nativeDate: "15 do 1º mês lunar",
  },
  {
    id: "cn-qingming",
    religion: "chinese",
    date: "2026-04-05",
    nameOriginal: "清明節 Qīngmíng Jié",
    namePt: "Festival dos Ancestrais",
    description: "Dia dedicado à visita aos túmulos e homenagem aos antepassados.",
    nativeDate: "Qingming (清明)",
  },
  {
    id: "cn-dragonboat",
    religion: "chinese",
    date: "2026-06-19",
    nameOriginal: "端午節 Duānwǔ Jié",
    namePt: "Festival do Barco-Dragão",
    description: "Corridas de barcos-dragão em memória do poeta Qu Yuan.",
    nativeDate: "5 do 5º mês lunar",
    major: true,
  },
  {
    id: "cn-qixi",
    religion: "chinese",
    date: "2026-08-19",
    nameOriginal: "七夕節 Qīxī Jié",
    namePt: "Noite dos Setes",
    description: "Festa tradicional dos amantes, baseada no mito do Pastor e da Tecelã.",
    nativeDate: "7 do 7º mês lunar",
  },
  {
    id: "cn-midautumn",
    religion: "chinese",
    date: "2026-09-25",
    nameOriginal: "中秋節 Zhōngqiū Jié",
    namePt: "Festival do Meio-Outono",
    description: "Festa da lua cheia, da família e dos bolos lunares.",
    nativeDate: "15 do 8º mês lunar",
    major: true,
  },
  {
    id: "cn-chongyang",
    religion: "chinese",
    date: "2026-10-18",
    nameOriginal: "重陽節 Chóngyáng Jié",
    namePt: "Festival do Duplo Nove",
    description: "Dia dedicado ao respeito pelos idosos e a passeios em montanhas.",
    nativeDate: "9 do 9º mês lunar",
  },
  {
    id: "cn-winter",
    religion: "chinese",
    date: "2026-12-22",
    nameOriginal: "冬至 Dōngzhì",
    namePt: "Solstício de Inverno",
    description: "Reunião familiar tradicional em torno de tangyuan, bolinhos de arroz.",
    nativeDate: "Dōngzhì",
  },
]

export function holidaysByDate(date: string): Holiday[] {
  return HOLIDAYS.filter((h) => h.date === date)
}

export function holidaysInMonth(year: number, month: number): Holiday[] {
  // month: 0-indexed
  const monthStr = String(month + 1).padStart(2, "0")
  const prefix = `${year}-${monthStr}`
  return HOLIDAYS.filter((h) => h.date.startsWith(prefix))
}
